routes/web.php
<?php


use App\Http\Controllers\AdminController;
use App\Http\Controllers\CustomAuthController;
use App\Http\Controllers\UserAuthController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
// Route::get('/index', function () {
//     return view('index');
// })->name('index');
// Route::get('/login', function () {
//     return view('auth.login');
// })->name('login');
// route::prefix('cms/admin')->middleware('guest:admin')->group(function(){
    // });
Route::resource('admins', AdminController::class);

// Route::get('{guard}/login',[UserAuthController::class,'showLogin'])->middleware('guest:admin')->name('login.viwe');
// Route::post('{guard}/login',[UserAuthController::class,'Login'])->middleware('guest:admin');


Route::get('index', [CustomAuthController::class, 'index2'])->name('index');
Route::get('login', [CustomAuthController::class, 'index'])->name('login');
Route::post('custom-login', [CustomAuthController::class, 'customLogin'])->name('login.custom'); 
Route::get('registration', [CustomAuthController::class, 'registration'])->name('register-user');
Route::post('custom-registration', [CustomAuthController::class, 'customRegistration'])->name('register.custom'); 
Route::get('signout', [CustomAuthController::class, 'signOut'])->name('signout');

resources/views/admin/create.blade.php
@extends('../index')
@section('title','create')
@section('content')
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Responsive Hover Table</h3>

          <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
              <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

              <div class="input-group-append">
                <button type="submit" class="btn btn-default">
                  <i class="fas fa-search"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">Quick Example</h3>
          </div>
          <!-- /.card-header -->
          <!-- form start -->
          <form id="create_form">
            @csrf
            <div class="card-body">
                <div class="form-group col-md-4">
                  <label for="email">Email address</label>
                  <input type="email" class="form-control" name="email" id="email" placeholder="Enter email">
                </div>
                <div class="form-group col-md-4">
                  <label for="password">Password</label>
                  <input type="password" class="form-control" name="password" id="password" placeholder="Password">
                </div>
                <div class="form-group col-md-4">
                  <label for="firstname">FirstName</label>
                <input type="text" class="form-control" name="firstname" id="firstname" placeholder="firstname">
              </div>
              <div class="form-group col-md-4">
                <label for="lastname">Last Name</label>
                <input type="text" class="form-control" name="lastname" id="lastname" placeholder="lastname">
              </div>
              <div class="form-group col-md-4">
                <label for="image">Image</label>
                <input type="text" class="form-control" name="image" id="image" placeholder="image">
              </div>
              <div class="form-group col-md-4">
                <label for="mobile">Mobile</label>
                <input type="text" class="form-control" name="mobile" id="mobile" placeholder="mobile">
              </div>
              <div class="form-group col-md-4">
                <label for="gender">Gender</label>
                <select class="form-control" name="gender" id="gender">
                  <option selected>Gender</option>
                  <option value="Male">Male</option>
                  <option value="Female">Female</option>
                </select>
              </div>
              <div class="form-group col-md-4">
                <label for="status">Status</label>
                <select class="form-control" name="status" id="status">
                  <option selected>Status</option>
                  <option value="Active">Active</option>
                  <option value="InActive">InActive</option>
                </select>
              </div>
              <div class="form-group col-md-4">
                <label for="dateOfBirth">Date Of Birth</label>
                <input type="text" class="form-control" name="dateOfBirth" id="dateOfBirth" placeholder="dateOfBirth">
              </div>
              {{-- <div class="form-group col-md-4">
                <label for="exampleInputFile">File input</label>
                <div class="input-group">
                  <div class="custom-file">
                    <input type="file" class="custom-file-input" id="exampleInputFile">
                    <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                  </div>
                  <div class="input-group-append">
                    <span class="input-group-text">Upload</span>
                  </div>
                </div>
              </div>
              <div class="form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
              </div>
            </div> --}}
            <!-- /.card-body -->

            <div class="card-footer">
              <button type="button" onclick="performStore()" class="btn btn-primary">store</button>
            </div>
          </form>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>
@endsection
@section('script')
<script>
  function performStore(){
    let data = {
      email: document.getElementById('email').value,
      password: document.getElementById('password').value,
      firstname: document.getElementById('firstname').value,
      lastname: document.getElementById('lastname').value,
      image: document.getElementById('image').value,
      mobile: document.getElementById('mobile').value,
      gender: document.getElementById('gender').value,
      status: document.getElementById('status').value,
      dateOfBirth: document.getElementById('dateOfBirth').value,
    }
    store('/admins',data);
  }
  </script>
@endsection

resources/views/admin/edit.blade.php
@extends('../index')
@section('title','create')
@section('content')
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Responsive Hover Table</h3>

          <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
              <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

              <div class="input-group-append">
                <button type="submit" class="btn btn-default">
                  <i class="fas fa-search"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">Quick Example</h3>
          </div>
          <!-- /.card-header -->
          <!-- form start -->
          <form id="create_form">
            @csrf
            <div class="card-body">
                <div class="form-group col-md-4">
                  <label for="email">Email address</label>
                  <input type="email" class="form-control" name="email" id="email" value="{{$admins->email}}" placeholder="Enter email">
                </div>
                <div class="form-group col-md-4">
                  <label for="firstname">FirstName</label>
                <input type="text" class="form-control" name="firstname" id="firstname" value="{{$admins->user->firstname}}"placeholder="firstname">
              </div>
              <div class="form-group col-md-4">
                <label for="lastname">Last Name</label>
                <input type="text" class="form-control" name="lastname" id="lastname" value="{{$admins->user->lastname}}"placeholder="lastname">
              </div>
              <div class="form-group col-md-4">
                <label for="image">Image</label>
                <input type="text" class="form-control" name="image" id="image" value="{{$admins->user->image}}" placeholder="image">
              </div>
              <div class="form-group col-md-4">
                <label for="mobile">Mobile</label>
                <input type="text" class="form-control" name="mobile" id="mobile" value="{{$admins->user->mobile}}"placeholder="mobile">
              </div>
              <div class="form-group col-md-4">
                <label for="gender">Gender</label>
                <select class="form-control" name="gender" id="gender">
                  <option selected>{{$admins->user->gender}}</option>
                  <option value="Male">Male</option>
                  <option value="Female">Female</option>
                </select>
              </div>
              <div class="form-group col-md-4">
                <label for="status">Status</label>
                <select class="form-control" name="status" id="status">
                  <option selected>{{$admins->user->status}}</option>
                  <option value="Active">Active</option>
                  <option value="InActive">InActive</option>
                </select>
              </div>
              <div class="form-group col-md-4">
                <label for="dateOfBirth">Date Of Birth</label>
                <input type="text" class="form-control" name="dateOfBirth" value="{{$admins->user->dateOfBirth}}"id="dateOfBirth" placeholder="dateOfBirth">
              </div>
              {{-- <div class="form-group col-md-4">
                <label for="exampleInputFile">File input</label>
                <div class="input-group">
                  <div class="custom-file">
                    <input type="file" class="custom-file-input" id="exampleInputFile">
                    <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                  </div>
                  <div class="input-group-append">
                    <span class="input-group-text">Upload</span>
                  </div>
                </div>
              </div>
              <div class="form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
              </div>
            </div> --}}
            <!-- /.card-body -->

            <div class="card-footer">
              <button type="button" onclick="performUpdate({{$admins->id}})" class="btn btn-primary">update</button>
            </div>
          </form>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>
@endsection
@section('script')
<script>
  function performUpdate(id ){
    let data = {
      email: document.getElementById('email').value,
      firstname: document.getElementById('firstname').value,
      lastname: document.getElementById('lastname').value,
      image: document.getElementById('image').value,
      mobile: document.getElementById('mobile').value,
      gender: document.getElementById('gender').value,
      status: document.getElementById('status').value,
      dateOfBirth: document.getElementById('dateOfBirth').value,
    }
    let redirectUrl = '/admins';
    update('/admins/'+id,data ,redirectUrl );
  }
  </script>
@endsection

resources/views/admin/index.blade.php
@extends('../index')
@section('title','index') 
@section('content')
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Responsive Hover Table</h3>

          <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
              <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

              <div class="input-group-append">
                <button type="submit" class="btn btn-default">
                  <i class="fas fa-search"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table table-hover text-nowrap">
            <thead>
              <tr>
                <th>ID</th>
                <th>Email</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Image</th>
                <th>Mobile</th>
                <th>Gender</th>
                <th>Status</th>
                <th>Date Of Birth</th>
                <th>Created At</th>
                <th>Updated At</th>
              </tr>
            </thead>
            <tbody>
              @foreach ($admins as $admin)
                <tr>
                  <td>{{$admin->id}}</td>
                  <td>{{$admin->email}}</td>
                  <td>{{$admin->user ? $admin->user->firstname:"NULL"}}</td>
                  <td>{{$admin->user ? $admin->user->lastname:"NULL"}}</td>
                  <td>{{$admin->user ? $admin->user->image:"NULL"}}</td>
                  <td>{{$admin->user ? $admin->user->mobile:"NULL"}}</td>
                  <td>{{$admin->user ? $admin->user->gender:"NULL"}}</td>
                  <td>{{$admin->user ? $admin->user->status:"NULL"}}</td>
                  <td>{{$admin->user ? $admin->user->dateOfBirth:"NULL"}}</td>
                  <td>{{$admin->created_at}}</td>
                  <td>{{$admin->updated_at}}</td>
                  <td>
                    <div class="btn-group">
                      <a href="{{ route('admins.edit',$admin->id) }}" type="button" class="btn btn-info btn-flat">
                        <i class="fas fa-edit"></i>
                      </a>
                      <a href="#" onclick="performDestroy({{$admin->id}},this)" class="btn btn-danger btn-flat">
                        <i class="fas fa-trash-alt"></i>
                      </a>
                      </form>
                    </div>
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
        </div>
        {{ $admins->links() }}
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>
@endsection
@section('script')
<script>
  function performDestroy(id,ref){
    confirmDestroy('/admins/'+id,ref)
  }
</script>
@endsection